title: "CodeWise - Formations pour développeurs"
email: "themeaffairs@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
 CodeWise - Formations pour développeurs. Des formations techniques, soft-skills, management.
baseurl: # the subpath of your site, e.g. /blog
url: https://codewise.fr # the base hostname & protocol for your site, e.g. http://example.com or  https://tradejk.netlify.com
blog-url: https://blog.codewise.fr
facebook_url: 
twitter_url: 
github_url:  https://github.com/hubergerard
pinterest_url: 
linkedin_url: https://www.linkedin.com/company/codewise-formation
instagram_url: 
logo: "/assets/img/logo/logo.png"
logo_2: "/assets/img/logo/logo2.png"
mailchimp_list: "https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=342411fb35"
mailchimp_input_name: "b_307862c135e4548eecf86f389_342411fb35"
author: "Huber GERARD"
permalink: "/:title"


# Build settings
markdown: kramdown
theme: minima

cover_image: "/assets/img/bg/page-title.png"


#collections
collections:
  features:
    output: true
  services:
    output: true